events {}

http {
    server {
        listen 80;

        location /api/transactions {
            proxy_pass http://transactions:6000/api/transactions;
        }

        location /api/ {
            proxy_pass http://backend:5000;
        }

        location / {
            proxy_pass http://studentportfolio:80;
        }
    }
}